from __future__ import annotations

from typing import Protocol

from app.domain.entities import (
    Artifact,
    Asset,
    AssetHandoff,
    Employee,
    Job,
    ProductionJob,
    ProviderConfig,
    SocialAccount,
    AuditEvent,
    WorkspaceSettings,
    Workflow,
    WorkflowRun,
)


class EmployeeRepository(Protocol):
    def list(self) -> list[Employee]: ...

    def get(self, employee_id: str) -> Employee | None: ...


class JobRepository(Protocol):
    def list(self) -> list[Job]: ...

    def get(self, job_id: str) -> Job | None: ...

    def create(self, job: Job) -> Job: ...

    def save(self, job: Job) -> Job: ...

    def add_artifact(self, artifact: Artifact) -> Artifact: ...


class WorkflowRepository(Protocol):
    def list(self) -> list[Workflow]: ...

    def get(self, workflow_id: str) -> Workflow | None: ...

    def create(self, workflow: Workflow) -> Workflow: ...

    def save(self, workflow: Workflow) -> Workflow: ...

    def delete(self, workflow_id: str) -> bool: ...

    def list_runs(self, workflow_id: str | None = None) -> list[WorkflowRun]: ...

    def get_run(self, run_id: str) -> WorkflowRun | None: ...

    def create_run(self, run: WorkflowRun) -> WorkflowRun: ...

    def save_run(self, run: WorkflowRun) -> WorkflowRun: ...


class AssetRepository(Protocol):
    def list(
        self,
        query: str | None = None,
        source_type: str | None = None,
        kind: str | None = None,
        status: str | None = None,
    ) -> list[Asset]: ...

    def get(self, asset_id: str) -> Asset | None: ...

    def find_by_source(self, source_type: str, source_id: str) -> list[Asset]: ...

    def create(self, asset: Asset) -> Asset: ...

    def save(self, asset: Asset) -> Asset: ...

    def list_handoffs(self, asset_id: str | None = None) -> list[AssetHandoff]: ...

    def create_handoff(self, handoff: AssetHandoff) -> AssetHandoff: ...


class ProductionRepository(Protocol):
    def list_jobs(
        self, target: str | None = None, status: str | None = None
    ) -> list[ProductionJob]: ...

    def get_job(self, job_id: str) -> ProductionJob | None: ...

    def create_job(self, job: ProductionJob) -> ProductionJob: ...

    def save_job(self, job: ProductionJob) -> ProductionJob: ...

    def seed_accounts(self, accounts: list[SocialAccount]) -> None: ...

    def list_accounts(self) -> list[SocialAccount]: ...

    def get_account(self, account_id: str) -> SocialAccount | None: ...

    def create_account(self, account: SocialAccount) -> SocialAccount: ...

    def save_account(self, account: SocialAccount) -> SocialAccount: ...


class AdminRepository(Protocol):
    def get_workspace(self) -> WorkspaceSettings: ...

    def save_workspace(self, settings: WorkspaceSettings) -> WorkspaceSettings: ...

    def seed_providers(self, providers: list[ProviderConfig]) -> None: ...

    def list_providers(self) -> list[ProviderConfig]: ...

    def create_audit_event(self, event: AuditEvent) -> AuditEvent: ...

    def list_audit_events(self, limit: int = 100) -> list[AuditEvent]: ...

    def count_records(self) -> dict[str, int]: ...

    def export_records(self) -> dict[str, list[dict]]: ...
