from __future__ import annotations

from typing import Protocol

from app.domain.entities import Artifact, Employee, Job, Workflow, WorkflowRun


class EmployeeRepository(Protocol):
    def list(self) -> list[Employee]: ...

    def get(self, employee_id: str) -> Employee | None: ...


class JobRepository(Protocol):
    def list(self) -> list[Job]: ...

    def get(self, job_id: str) -> Job | None: ...

    def create(self, job: Job) -> Job: ...

    def save(self, job: Job) -> Job: ...

    def add_artifact(self, artifact: Artifact) -> Artifact: ...


class WorkflowRepository(Protocol):
    def list(self) -> list[Workflow]: ...

    def get(self, workflow_id: str) -> Workflow | None: ...

    def create(self, workflow: Workflow) -> Workflow: ...

    def save(self, workflow: Workflow) -> Workflow: ...

    def delete(self, workflow_id: str) -> bool: ...

    def list_runs(self, workflow_id: str | None = None) -> list[WorkflowRun]: ...

    def get_run(self, run_id: str) -> WorkflowRun | None: ...

    def create_run(self, run: WorkflowRun) -> WorkflowRun: ...

    def save_run(self, run: WorkflowRun) -> WorkflowRun: ...
